### PR TITLE
Question 1 -- #1

### PR DESCRIPTION
**Pull request by aradu12**
Finished #1 -- 

- added a helper function to validate year input, since it's common to most queries
- added 1.sql, which generates monthly crime numbers as totals over a given year range
-- uses a left join to get 0 for months with no crime
- added code to generate the bar plot and save it

Possible edits:
- could make the plot look a little snazzier (add a title, border, etc.)
- could alter input validation to completely reject ranges like [2010,2009] (since by default no results from backwards range). Currently, they are accepted but it produces an (obviously) empty bar plot

Any other suggestions?

### CODE REVIEW

**Comment by NinjaPerson24119** [comment]
Naming scheme for generated files is wrong. Should be in the form {Question-Number}-{count}, e.g., Q1-1.png, Q2-1.html etc., where count will be updated each time they are executed.

You should make a helper function for generating file names.

**Comment by NinjaPerson24119** [comment]
Can you enumerate some test cases and build an appropriate DB? The graph and code looks good, but there's so much data that it's impossible for me to validate its contents.

**Comment by NinjaPerson24119** [comment]
The year ranges should be strictly ordered. 2010-2009 is definitely an error.
I'd appreciate a title on the graph since the file name can't be descriptive.

**Comment by aradu12** [comment]
- addressed your comments: added call counting, plot title, and ordered year validation
- will address your comment re: testing cases/DB by tomorrow

**Comment by NinjaPerson24119** [comment]
Everything so far looks fine. Just need tests now.

**Comment by hughbagan** [comment]
Found an edge case: the user can still enter years that are outside the dataset, like 1 or 2008 or 2019. It doesn't crash the program or affect the resulting graph. Not a big deal, but if you want to fix it then you can copy my `3c.sql`. Other than that I think it looks good.

**Comment by aradu12** [comment]
Hi hugh,
I considered that edge case when writing the program and made that functionality intentional. Here is my reasoning:
- though a year may be outside the database range, it doesn't necessarily mean it will always be. The government could conceivably dig up old data from 2006, 1985, or even 1940, and add it to the database. I thought calculating the minimum and maximum years in the database on every run would be too costly.

**Comment by aradu12** [comment]
Though, since the data from the range [2006,2010] would be exactly the same as [2009,2010], you could argue that the output is misleading, making it look like there were less crimes per year on average. 
On the other hand, theres no guarantee the results for years in the database are correct, since it all depends on the accuracy of the dataset. Maybe there were a lot more crimes in 2009, but they haven't gotten around to entering all of them into the db. One could argue this is also misleading.
Either way, what do u think? Better to leave as is, or calculate the minimum year on each run? Could also decide on some arbitrary minimum year like 1950 (right now it is 0)

**Comment by aradu12** [comment]
Also added some simple tests. I did the tests using the sampled DB, and calculated expected results manually. I don't believe any more intense testing is needed, especially because of this manual portion.

**Comment by NinjaPerson24119** [comment]
I actually don't see how those tests are useful. I wanted to have a minimal DB that I could inspect. The whole point was to avoid using the full data set by first checking if it worked on a smaller, more intuitive DB.

**Comment by NinjaPerson24119** [comment]
I can't easily interpret your tests without scanning the online database. Which is what I wanted to avoid. You actually did more work than is necessary.

**Comment by NinjaPerson24119** [comment]
FWIW, lgtm on basic inspection

**Review by NinjaPerson24119 — APPROVED** [review]
Looks good enough to me

**Comment by hughbagan** [comment]
> Either way, what do u think?

(The only thing this affects is the title of the graph really, so I think it's OK as it is!)

**Review by hughbagan — APPROVED** [review]

**Pull request merged**
