### PR TITLE
Task4

### PR DESCRIPTION
**Pull request by NinjaPerson24119**
Idk why my map doesn't match the example on eclass

### CODE REVIEW

**Comment by hughbagan** [comment]
- looks like there's a print statement of the data structure. Not a big deal, but we probably want to hide that from the user.

- the resulting map had dozens of neighbourhoods on it. I think in the for loop in your mapping you meant to iterate over `topCrimes` instead of `rows`. 

- might not be a bad idea to restrict the input a bit more, I could still input negative years 

- Don't forget to rename the task in the main menu!

**Comment by aradu12** [comment]
Hmmm, I'm seeing a lot of issues here. In addition to what Hugh said:
- When the year range is not in the database (e.x., [2005,2008]), the program does nothing. I think it would be better to either generate an empty map OR to alert the user that there was no data obtained, so they are not confused as to why it suddenly exits.

- When you get user input, you exit the task in the case of invalid input (e.x.,a string instead of an int). I think it would be better to have a loop and prompt the user again until the input is valid. You can look at what I did for task 1, with my `get_valid_year` function

- I would also suggest making the bubbles on the map bigger

**Comment by NinjaPerson24119** [comment]
- fixed validation
- bubbles slightly bigger.
- had forgotten to uncomment top-n loop for breaking at n. Now shows n elements.
- renamed task

**Review by aradu12 — APPROVED** [review]
lgtm

**Pull request merged**
