### PR TITLE
Hughbranch

### PR DESCRIPTION
**Pull request by hughbagan**
I did some testing already and it seems pretty good. If you find any bugs let me know.

### CODE REVIEW

**Comment by NinjaPerson24119** [comment]
Without a minimal test DB, it's really hard to tell if any of the results are correct.

**Comment by NinjaPerson24119** [comment]
2 definitely doesn't work. I put n=2 and the map displayed like 8 regions

**Comment by NinjaPerson24119** [comment]
3 definitely doesn't work. Fails to match the eclass example for 2011-2013 n=3 crime=assault

**Comment by hughbagan** [comment]
> 2 definitely doesn't work. I put n=2 and the map displayed like 8 regions

What does your DB look like? I test Task 2 with `a4-sampled.db` from eclass, input N=2, and it plots 4 neighbourhoods as expected (2 most populous and 2 least populous). Another thing to consider is that it includes tied populations just like the last assignment (this is specified on eClass) so that might be at play in your output. I'm getting correct output on my end so I'd need more information if something isn't working.

> 3 definitely doesn't work. Fails to match the eclass example for 2011-2013 n=3 crime=assault

I'm fairly certain that the eclass example is not using the same data and is intended to just be a mockup. I find it hard to believe that _Aldergrove_, a quiet neighbourhood on the west end, would be leading the city with only 46 assaults over a two-year time span. Our program's output, on the other hand, says it's Downtown 235, Boyle Street 224, and McCauley 190 which sounds more like the real dataset. You can see the query for yourself if you like:

`select Neighbourhood_Name, sum(Incidents_Count) as count from crime_incidents where Crime_Type="Assault" and Year>=2011 and Year<=2013 group by Neighbourhood_Name order by count desc;`

**Comment by NinjaPerson24119** [comment]
You're right. In general, the example images are wrong.

I think the code is fine.

**Comment by NinjaPerson24119** [comment]
I actually didn't notice that the output is 2n points. That looks fine then.

**Review by NinjaPerson24119 — APPROVED** [review]

**Review by aradu12 — APPROVED** [review]
just a couple merge conflicts that shouldn't be too hard to fix

**Pull request merged**
